host: "127.0.0.1"
port: 8080
botType: "minimax"
depth: 3
guiType: "window"
windowDelay: 0
playerColor: "BLACK"
nickname: "никита"
numberOfGames: 1000000
logPath: "/home/nikita/local_client/logs/"
logFile: "client.log"