host: "127.0.0.1"
port: 8080
botType: "ab pruning"
depth: 5
guiType: "empty"
windowDelay: 0
playerColor: "BLACK"
nickname: "nikita"
numberOfGames: 100
logPath: "/home/nikita/local_client/logs/"
logFile: "client.log"